### ISSUE TITLE
Web Scraping

### ISSUE THREAD

**Issue by jemisonf** [OSU-CS290-F17/final-project-asdfas#2]
- [x] take a subject code, class number and term as command line input
- [ ] ~~copy http calls of scheduler~~
- [x] Fallback: Go to OSU course catalog site using format: `http://catalog.oregonstate.edu/CourseDetail.aspx?subjectcode={subjectcode}&coursenumber={coursenumber}`
- [x] Check if course actually exits and return some false value if not
- [ ] For prototype, get class and print to stdout and ignore MongoDB
- [ ] Get each class with seats open and return the class time, room and available seats in JSON format
- [ ] Put into readme.md how to get python + beautifulsoup working, and script running instructions

Stretch Goals:
- [ ] Get prerequisites for the class
- [ ] Get level restrictions/other restrictions for each class

Is this server side or client side? Need to decide

**Comment by gillens** [comment]
Have a python prototype using the BeautifulSoup library that can get course catalog data from a command line class and term arg and check if it exists. Working on the JSON output now.
